#!/usr/bin/env bash
#install nginx and redirects to hello world string
sudo apt-get -y update
sudo apt-get -y install nginx
file1=/usr/share/nginx/html/index.html
sudo bash -c "echo 'Hello world!' > $file1"
service nginx start
